apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/thainguyencoffee/music-service/k8s?ref=main

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: music-config

images:
- name: music-service
  newName: ghcr.io/thainguyencoffee/music-service
  newTag: 17d8265d2c5e056a378836a1ec9b7000450fbde0

replicas:
- count: 2
  name: music-service
