apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/thainguyencoffee/edge-service/k8s?ref=main

patches:
  - path: patch-env.yml
  - path: path-ingress.yml
  - path: patch-resources.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-prod.yml
    name: edge-config

images:
  - name: edge-service
    newName: ghcr.io/thainguyencoffee/edge-service
    newTag: latest

replicas:
  - count: 1
    name: edge-service